#!/usr/bin/env python2

# Copyright (C) 2011-2013 Red Hat, Inc.
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; If not, see <http://www.gnu.org/licenses/>.
#
# Author: tasleson

import sys
import syslog
import traceback

try:
    from lsm import PluginRunner
    from lsm.plugin.sim.simulator import SimPlugin

    if __name__ == '__main__':
        PluginRunner(SimPlugin, sys.argv).run()
except Exception:
    # This should be quite rare, but when it does happen this is pretty
    # key in understanding what happened, especially when it happens when
    # running from the daemon.
    msg = str(traceback.format_exc())
    syslog.syslog(syslog.LOG_ERR, msg)
    sys.stderr.write(msg)
    sys.exit(1)
